### ISSUE TITLE
java.sql.SQLException and server crash!

### ISSUE THREAD

**Issue by herm1ne** [WirelessRedstoneGroup/WirelessRedstone#165]
I am still investigating reproduce procedure but I got huge problem.
When I activate WR by direct input or right-click on signs, or removes signs it sometimes throw the following exception and lead to crash the server.
I have never encountered server crash when placing sings or activate WR by command yet.

server spec:
Windows 2016 64bit
RAM 10GB
CPU Xeon E5
Spigot 1.8.8
WR: 2.6.1

```
[Sun Dec 11 14:50:41 JST 2016 WARN] java.sql.SQLException: database table is locked
[Sun Dec 11 14:50:41 JST 2016 WARN]     at org.sqlite.NativeDB.throwex(NativeDB.java:210)
[Sun Dec 11 14:50:41 JST 2016 WARN]     at org.sqlite.NativeDB._exec(Native Method)
[Sun Dec 11 14:50:41 JST 2016 WARN]     at org.sqlite.Stmt.executeUpdate(Stmt.java:152)
[Sun Dec 11 14:50:41 JST 2016 WARN]     at net.licks92.WirelessRedstone.Configuration.SQLiteStorage.removeWirelessChannel(SQLiteStorage.java:540)
[Sun Dec 11 14:50:41 JST 2016 WARN]     at net.licks92.WirelessRedstone.Configuration.WirelessConfiguration.removeWirelessChannel(WirelessConfiguration.java:317)
[Sun Dec 11 14:50:41 JST 2016 WARN]     at net.licks92.WirelessRedstone.Listeners.WirelessBlockListener.onBlockBreak(WirelessBlockListener.java:361)
[Sun Dec 11 14:50:41 JST 2016 WARN]     at sun.reflect.GeneratedMethodAccessor347.invoke(Unknown Source)
[Sun Dec 11 14:50:41 JST 2016 WARN]     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[Sun Dec 11 14:50:41 JST 2016 WARN]     at java.lang.reflect.Method.invoke(Method.java:498)
[Sun Dec 11 14:50:41 JST 2016 WARN]     at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306)
[Sun Dec 11 14:50:41 JST 2016 WARN]     at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[Sun Dec 11 14:50:41 JST 2016 WARN]     at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)
[Sun Dec 11 14:50:41 JST 2016 WARN]     at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487)
[Sun Dec 11 14:50:41 JST 2016 WARN]     at net.minecraft.server.v1_8_R3.PlayerInteractManager.breakBlock(PlayerInteractManager.java:286)
[Sun Dec 11 14:50:41 JST 2016 WARN]     at net.minecraft.server.v1_8_R3.PlayerInteractManager.a(PlayerInteractManager.java:121)
[Sun Dec 11 14:50:41 JST 2016 WARN]     at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:623)
[Sun Dec 11 14:50:41 JST 2016 WARN]     at net.minecraft.server.v1_8_R3.PacketPlayInBlockDig.a(SourceFile:40)
[Sun Dec 11 14:50:41 JST 2016 WARN]     at net.minecraft.server.v1_8_R3.PacketPlayInBlockDig.a(SourceFile:10)
[Sun Dec 11 14:50:41 JST 2016 WARN]     at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)
[Sun Dec 11 14:50:41 JST 2016 WARN]     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[Sun Dec 11 14:50:41 JST 2016 WARN]     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[Sun Dec 11 14:50:41 JST 2016 WARN]     at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44)
[Sun Dec 11 14:50:41 JST 2016 WARN]     at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715)
[Sun Dec 11 14:50:41 JST 2016 WARN]     at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
[Sun Dec 11 14:50:41 JST 2016 WARN]     at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
[Sun Dec 11 14:50:41 JST 2016 WARN]     at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
[Sun Dec 11 14:50:41 JST 2016 WARN]     at java.lang.Thread.run(Thread.java:745)
```

**Comment by Bart-0110** [comment]
Can you update to the latest version (2.6.7)? It maybe fixed already.

**Comment by herm1ne** [comment]
Hi thanks for the reply!
I updated both spigot(1.8.8 latest build) and WR (2.6.7) but the error still sometimes occur.
```
[Mon Dec 12 17:38:32 JST 2016 WARN] java.sql.SQLException: database table is locked
[Mon Dec 12 17:38:32 JST 2016 WARN]     at org.sqlite.NativeDB.throwex(NativeDB.java:210)
[Mon Dec 12 17:38:32 JST 2016 WARN]     at org.sqlite.NativeDB._exec(Native Method)
[Mon Dec 12 17:38:32 JST 2016 WARN]     at org.sqlite.Stmt.executeUpdate(Stmt.java:152)
[Mon Dec 12 17:38:32 JST 2016 WARN]     at net.licks92.WirelessRedstone.Configuration.SQLiteStorage.removeWirelessChannel(SQLiteStorage.java:540)
[Mon Dec 12 17:38:32 JST 2016 WARN]     at net.licks92.WirelessRedstone.Configuration.WirelessConfiguration.removeWirelessChannel(WirelessConfiguration.java:316)
[Mon Dec 12 17:38:32 JST 2016 WARN]     at net.licks92.WirelessRedstone.Listeners.WirelessBlockListener.onBlockBreak(WirelessBlockListener.java:322)
[Mon Dec 12 17:38:32 JST 2016 WARN]     at sun.reflect.GeneratedMethodAccessor252.invoke(Unknown Source)
[Mon Dec 12 17:38:32 JST 2016 WARN]     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[Mon Dec 12 17:38:32 JST 2016 WARN]     at java.lang.reflect.Method.invoke(Method.java:498)
[Mon Dec 12 17:38:32 JST 2016 WARN]     at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306)
[Mon Dec 12 17:38:32 JST 2016 WARN]     at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[Mon Dec 12 17:38:32 JST 2016 WARN]     at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)
[Mon Dec 12 17:38:32 JST 2016 WARN]     at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487)
[Mon Dec 12 17:38:32 JST 2016 WARN]     at net.minecraft.server.v1_8_R3.PlayerInteractManager.breakBlock(PlayerInteractManager.java:286)
[Mon Dec 12 17:38:32 JST 2016 WARN]     at net.minecraft.server.v1_8_R3.PlayerInteractManager.a(PlayerInteractManager.java:121)
[Mon Dec 12 17:38:32 JST 2016 WARN]     at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:623)
[Mon Dec 12 17:38:32 JST 2016 WARN]     at net.minecraft.server.v1_8_R3.PacketPlayInBlockDig.a(SourceFile:40)
[Mon Dec 12 17:38:32 JST 2016 WARN]     at net.minecraft.server.v1_8_R3.PacketPlayInBlockDig.a(SourceFile:10)
[Mon Dec 12 17:38:32 JST 2016 WARN]     at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)
[Mon Dec 12 17:38:32 JST 2016 WARN]     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[Mon Dec 12 17:38:32 JST 2016 WARN]     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[Mon Dec 12 17:38:32 JST 2016 WARN]     at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44)
[Mon Dec 12 17:38:32 JST 2016 WARN]     at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715)
[Mon Dec 12 17:38:32 JST 2016 WARN]     at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
[Mon Dec 12 17:38:32 JST 2016 WARN]     at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
[Mon Dec 12 17:38:32 JST 2016 WARN]     at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
[Mon Dec 12 17:38:32 JST 2016 WARN]     at java.lang.Thread.run(Thread.java:745)
```

Could you look into this?
Please let me know if you need something.

**Comment by herm1ne** [comment]
okay, I don't know the relationship to this bug, but I found another thing which you may be interested in.  

**< Real Settings>**
1 receiver, 2 transmitters, 0 screens
__Receiver__ pos: -1121 55 1648
__Transmitter1__ pos: -1136 56 1635
__Transmitter2__ pos: -1116 55 1641

**<When I type "/wr info taitaizikkenn (transmitter|receiver)">**
The positions show correctly...
![image](https://cloud.githubusercontent.com/assets/5259790/21102614/3778e342-c0c2-11e6-847a-19c29e671487.png)
BUT
When I click on these to teleport...
The top one: tp me to **receiver**
Middle one: **Aｎ internal error occurred while attempting to perform this command** but no exception in console (No tp)
Bottom one: tp me to receiver (The same pos as top one) <- works fine

----
And we found the exception and massive TPS drop can occur when we place/break WR signs as well.

**Comment by Bart-0110** [comment]
Okay if the problem still exist and you have problems with TPS (probably because it want to access the database on the main thread) I recommend to downgrade back to 2.6.1.

The teleport issues should be fixed with the new update. 
I think the internal exception occurred when contacting the database but it couldn't handle the request.

I'm sorry for all the problems, I'm trying to fix everything.

**Comment by herm1ne** [comment]
The issue initially appeared on 2.6.1...
but please give me few days so I reverse version further more and see if it works.

**Comment by Bart-0110** [comment]
Okay, can you otherwise check this new beta version? I changed the way it accesses the global cache so it should release a lot of strain from the database.

https://github.com/WirelessRedstoneGroup/WirelessRedstone/releases/tag/v3.0.0-beta

**Comment by herm1ne** [comment]
Thanks for the beta out!  
Using the beta for 10 minute, creating and removing channels but have not encountered TPS drop yet.
Still need to use up before closing issue :hugs: 
I appreciate your fast response as this plugin is essential for my server.

**Comment by herm1ne** [comment]
I encounter some exceptions, however, I did not encounter any massive TPS drop so this issue is closed.
Fixed on beta-v3.0.0

**Comment by Bart-0110** [comment]
Can you share those exceptions so I can try to fix them?

**Comment by herm1ne** [comment]
Of course! I just submit a new issue 👍
