### ISSUE TITLE
WR 3.0 beta (server) Error on shutdown

### ISSUE THREAD

**Issue by wapjoe** [WirelessRedstoneGroup/WirelessRedstone#169]
Hello,

on shutdown or restarting the Server, i'm getting the following messages from WR:

`[00:30:18] [Server thread/INFO]: Stopping the server
[00:30:18] [Server thread/INFO]: Stopping server
[00:30:18] [Server thread/INFO]: [WirelessRedstone] Disabling WirelessRedstone v3.0.0-beta
[00:30:18] [Server thread/INFO]: [0;31;1m[WirelessRedstone][m[0;31;22m[SEVERE] [mAn error occured when disabling the plugin![m
[00:30:18] [Server thread/WARN]: org.bukkit.plugin.IllegalPluginAccessException: Plugin attempted to register task while disabled
[00:30:18] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.validate(CraftScheduler.java:403)
[00:30:18] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.runTaskTimerAsynchronously(CraftScheduler.java:144)
[00:30:18] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.runTaskLaterAsynchronously(CraftScheduler.java:118)
[00:30:18] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.runTaskAsynchronously(CraftScheduler.java:101)
[00:30:18] [Server thread/WARN]: 	at net.licks92.WirelessRedstone.Libs.SQLite.execute(SQLite.java:128)
[00:30:18] [Server thread/WARN]: 	at net.licks92.WirelessRedstone.Libs.SQLite.execute(SQLite.java:117)
[00:30:18] [Server thread/WARN]: 	at net.licks92.WirelessRedstone.Storage.SQLiteStorage.updateSwitch(SQLiteStorage.java:946)
[00:30:18] [Server thread/WARN]: 	at net.licks92.WirelessRedstone.Storage.SQLiteStorage.updateReceivers(SQLiteStorage.java:851)
[00:30:18] [Server thread/WARN]: 	at net.licks92.WirelessRedstone.Main.onDisable(Main.java:97)
[00:30:18] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:273)
[00:30:18] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:361)
[00:30:18] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:424)
[00:30:18] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:417)
[00:30:18] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.disablePlugins(CraftServer.java:344)
[00:30:18] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.MinecraftServer.stop(MinecraftServer.java:462)
[00:30:18] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:610)
[00:30:18] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:745)`

I dont know if it's bad, WR is running normal. May you can use this messages to debugging. 

wapjoe :-)

**Comment by Bart-0110** [comment]
Thank you. I'll fix it for the release

**Comment by Bart-0110** [comment]
Hi, can you try this build? 

https://github.com/WirelessRedstoneGroup/WirelessRedstone/releases/tag/v3.0.0-beta.2

**Comment by wapjoe** [comment]
Hi, it's still the same:

`[21:14:45] [Server thread/INFO]: Stopping the server
[21:14:45] [Server thread/INFO]: Stopping server
[21:14:45] [Server thread/INFO]: [WirelessRedstone] Disabling WirelessRedstone v3.0.0-beta.2
[21:14:45] [Server thread/INFO]: [0;31;1m[WirelessRedstone][m[0;31;22m[SEVERE] [mAn error occured when disabling the plugin![m
[21:14:45] [Server thread/WARN]: org.bukkit.plugin.IllegalPluginAccessException: Plugin attempted to register task while disabled
[21:14:45] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.validate(CraftScheduler.java:403)
[21:14:45] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.runTaskTimerAsynchronously(CraftScheduler.java:144)
[21:14:45] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.runTaskLaterAsynchronously(CraftScheduler.java:118)
[21:14:45] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.runTaskAsynchronously(CraftScheduler.java:101)
[21:14:45] [Server thread/WARN]: 	at net.licks92.WirelessRedstone.GlobalCache.updateAllSigns(GlobalCache.java:37)
[21:14:45] [Server thread/WARN]: 	at net.licks92.WirelessRedstone.GlobalCache.update(GlobalCache.java:87)
[21:14:45] [Server thread/WARN]: 	at net.licks92.WirelessRedstone.GlobalCache.update(GlobalCache.java:83)
[21:14:45] [Server thread/WARN]: 	at net.licks92.WirelessRedstone.Storage.SQLiteStorage.updateSwitch(SQLiteStorage.java:948)
[21:14:45] [Server thread/WARN]: 	at net.licks92.WirelessRedstone.Storage.SQLiteStorage.updateReceivers(SQLiteStorage.java:851)
[21:14:45] [Server thread/WARN]: 	at net.licks92.WirelessRedstone.Main.onDisable(Main.java:97)
[21:14:45] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:273)
[21:14:45] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:361)
[21:14:45] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:424)
[21:14:45] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:417)
[21:14:45] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.disablePlugins(CraftServer.java:344)
[21:14:45] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.MinecraftServer.stop(MinecraftServer.java:462)
[21:14:45] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:610)
[21:14:45] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:745)
`
Here the Version of java on my server:
`java version "1.8.0_111"
Java(TM) SE Runtime Environment (build 1.8.0_111-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.111-b14, mixed mode)`

If you need more information about the server and plugins, pls. tell it! :-)

**Comment by wapjoe** [comment]
Today i getting also this message, after login into the game:

`[22:29:51 INFO]: [WirelessRedstone] Plugin is now loaded
[22:29:51 INFO]: Done (5,939s)! For help, type "help" or "?"
[22:54:46 INFO]: UUID of player wapjoe is 5706a419-cd41-4084-a904-ecbf159b4d0e
[22:54:46 INFO]: wapjoe[/192.168.198.101:51042] logged in with entity id 258 at ([world]3803.6759876174483, 143.0, 23.532134735040934)
[22:54:46 WARN]: [WirelessRedstone] Task #3378 for WirelessRedstone v3.0.0-beta.2 generated an exception
java.lang.NullPointerException
        at net.licks92.WirelessRedstone.Listeners.PlayerListener$1.run(PlayerListener.java:30) ~[?:?]
        at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.11.jar:git-Spigot-f950f8e-c4baa9c]
        at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [spigot-1.11.jar:git-Spigot-f950f8e-c4baa9c]
        at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:730) [spigot-1.11.jar:git-Spigot-f950f8e-c4baa9c]
        at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.11.jar:git-Spigot-f950f8e-c4baa9c]
        at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675) [spigot-1.11.jar:git-Spigot-f950f8e-c4baa9c]
        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574) [spigot-1.11.jar:git-Spigot-f950f8e-c4baa9c]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]`
