### ISSUE TITLE
SQL Exception again

### ISSUE THREAD

**Issue by herm1ne** [WirelessRedstoneGroup/WirelessRedstone#171]
Hi This is a little bit different from the past one but I start experiencing the sql error
```
[00:00:59] [Craft Scheduler Thread - 6008/WARN]: java.sql.SQLException: [SQLITE_ERROR] SQL error or missing database (unrecognized token: "0422y")
[00:00:59] [Craft Scheduler Thread - 6008/WARN]: 	at org.sqlite.DB.newSQLException(DB.java:383)
[00:00:59] [Craft Scheduler Thread - 6008/WARN]: 	at org.sqlite.DB.newSQLException(DB.java:387)
[00:00:59] [Craft Scheduler Thread - 6008/WARN]: 	at org.sqlite.DB.throwex(DB.java:374)
[00:00:59] [Craft Scheduler Thread - 6008/WARN]: 	at org.sqlite.NativeDB.prepare(Native Method)
[00:00:59] [Craft Scheduler Thread - 6008/WARN]: 	at org.sqlite.DB.prepare(DB.java:123)
[00:00:59] [Craft Scheduler Thread - 6008/WARN]: 	at org.sqlite.PrepStmt.<init>(PrepStmt.java:42)
[00:00:59] [Craft Scheduler Thread - 6008/WARN]: 	at org.sqlite.Conn.prepareStatement(Conn.java:404)
[00:00:59] [Craft Scheduler Thread - 6008/WARN]: 	at org.sqlite.Conn.prepareStatement(Conn.java:399)
[00:00:59] [Craft Scheduler Thread - 6008/WARN]: 	at org.sqlite.Conn.prepareStatement(Conn.java:383)
[00:00:59] [Craft Scheduler Thread - 6008/WARN]: 	at net.licks92.WirelessRedstone.Storage.SQLiteStorage.getWirelessChannel(SQLiteStorage.java:516)
[00:00:59] [Craft Scheduler Thread - 6008/WARN]: 	at net.licks92.WirelessRedstone.Storage.SQLiteStorage.getAllChannels(SQLiteStorage.java:469)
[00:00:59] [Craft Scheduler Thread - 6008/WARN]: 	at net.licks92.WirelessRedstone.GlobalCache.updateList(GlobalCache.java:52)
[00:00:59] [Craft Scheduler Thread - 6008/WARN]: 	at net.licks92.WirelessRedstone.GlobalCache.access$000(GlobalCache.java:13)
[00:00:59] [Craft Scheduler Thread - 6008/WARN]: 	at net.licks92.WirelessRedstone.GlobalCache$2.run(GlobalCache.java:39)
[00:00:59] [Craft Scheduler Thread - 6008/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
[00:00:59] [Craft Scheduler Thread - 6008/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
[00:00:59] [Craft Scheduler Thread - 6008/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[00:00:59] [Craft Scheduler Thread - 6008/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[00:00:59] [Craft Scheduler Thread - 6008/WARN]: 	at java.lang.Thread.run(Thread.java:745)
```

```
[00:11:15] [Craft Scheduler Thread - 6209/WARN]: org.apache.commons.lang.UnhandledException: Plugin WirelessRedstone v3.0.0-beta.2 generated an exception while executing task 9935
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at net.licks92.WirelessRedstone.Main$6.getValue(Main.java:260)
	at net.licks92.WirelessRedstone.Metrics.postPlugin(Metrics.java:407)
	at net.licks92.WirelessRedstone.Metrics.access$400(Metrics.java:49)
	at net.licks92.WirelessRedstone.Metrics$1.run(Metrics.java:215)
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
```

```
[02:35:27] [Server thread/ERROR]: Could not pass event SignChangeEvent to WirelessRedstone v3.0.0-beta.2
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1864) [spigot.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.PacketPlayInUpdateSign.a(SourceFile:49) [spigot.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.PacketPlayInUpdateSign.a(SourceFile:11) [spigot.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-21fe707-e1ebe52]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_102]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_102]
	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [spigot.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [spigot.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot.jar:git-Spigot-21fe707-e1ebe52]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_102]
Caused by: java.lang.NullPointerException
	at net.licks92.WirelessRedstone.Storage.SQLiteStorage.getWirelessChannel(SQLiteStorage.java:492) ~[?:?]
	at net.licks92.WirelessRedstone.Storage.SQLiteStorage.getWirelessChannel(SQLiteStorage.java:482) ~[?:?]
	at net.licks92.WirelessRedstone.SignManager.hasAccessToChannel(SignManager.java:461) ~[?:?]
	at net.licks92.WirelessRedstone.Listeners.BlockListener.onSignChange(BlockListener.java:46) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor617.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_102]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_102]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-21fe707-e1ebe52]
	... 15 more
```

```
[02:35:57] [Server thread/ERROR]: Could not pass event BlockBreakEvent to WirelessRedstone v3.0.0-beta.2
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.PlayerInteractManager.breakBlock(PlayerInteractManager.java:286) [spigot.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.PlayerInteractManager.a(PlayerInteractManager.java:121) [spigot.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:623) [spigot.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.PacketPlayInBlockDig.a(SourceFile:40) [spigot.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.PacketPlayInBlockDig.a(SourceFile:10) [spigot.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-21fe707-e1ebe52]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_102]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_102]
	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [spigot.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [spigot.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot.jar:git-Spigot-21fe707-e1ebe52]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_102]
Caused by: java.lang.NullPointerException
	at net.licks92.WirelessRedstone.Storage.SQLiteStorage.getWirelessChannel(SQLiteStorage.java:492) ~[?:?]
	at net.licks92.WirelessRedstone.Storage.SQLiteStorage.getWirelessChannel(SQLiteStorage.java:482) ~[?:?]
	at net.licks92.WirelessRedstone.SignManager.hasAccessToChannel(SignManager.java:461) ~[?:?]
	at net.licks92.WirelessRedstone.Listeners.BlockListener.onBlockBreak(BlockListener.java:185) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor317.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_102]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_102]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-21fe707-e1ebe52]
	... 17 more
```

The first and seconds error occurred periodically. The third and forth one is occurred when the specific event has triggered.  
I don't know whether the first error triggers 2nd ~ 4th errors but I just want to let you know.  
One interesting point is we have the player named "youtyan0422" on my server and it must be somehow connected to this error. (the first error indicates `unrecognized token: "0422y"` )  
Unfortunately, I cannot confirm that if there is a channel named `0422y` since when I type `/wr info 0422y` it threw exception as follows: (will not throw exception when I type other channel names)  
```
[03:18:31] [Server thread/INFO]: Ru1x issued server command: /wr info 0422y
[03:18:31] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'wr' in plugin WirelessRedstone v3.0.0-beta.2
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641) ~[spigot.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162) [spigot.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997) [spigot.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-21fe707-e1ebe52]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_102]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_102]
	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [spigot.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [spigot.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot.jar:git-Spigot-21fe707-e1ebe52]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_102]
Caused by: java.lang.NullPointerException
	at net.licks92.WirelessRedstone.Storage.SQLiteStorage.getWirelessChannel(SQLiteStorage.java:492) ~[?:?]
	at net.licks92.WirelessRedstone.Storage.SQLiteStorage.getWirelessChannel(SQLiteStorage.java:482) ~[?:?]
	at net.licks92.WirelessRedstone.Commands.Info.onCommand(Info.java:22) ~[?:?]
	at net.licks92.WirelessRedstone.Commands.CommandManager.onCommand(CommandManager.java:99) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot.jar:git-Spigot-21fe707-e1ebe52]
	... 15 more
```

I apologize for bringing this huge issue and thank you for your support!

**Comment by herm1ne** [comment]
Do you have a new build to fix this?

**Comment by Bart-0110** [comment]
Can you try this build?

[WirelessRedstone.zip](https://github.com/WirelessRedstoneGroup/WirelessRedstone/files/671788/WirelessRedstone.zip)

**Comment by herm1ne** [comment]
Hi
I tried the build above but the things went worth...
The plugin itself crashes when loaded and does not accept any command/sign place, break.
The error on load is below:
```
Console	: [19:06:19 INFO]: [WirelessRedstone] Enabling WirelessRedstone v3.0.0
Console	: [19:06:19 INFO]: [WirelessRedstone][WARNING] You've set the language to default in your configuration. This language isn't available. The plugin will use English as language.
Console	: [19:06:29 WARN]: java.sql.SQLException: [SQLITE_ERROR] SQL error or missing database (unrecognized token: "0422y")
Console	: [19:06:29 WARN]: 	at org.sqlite.DB.newSQLException(DB.java:383)
Console	: [19:06:29 WARN]: 	at org.sqlite.DB.newSQLException(DB.java:387)
Console	: [19:06:29 WARN]: 	at org.sqlite.DB.throwex(DB.java:374)
Console	: [19:06:29 WARN]: 	at org.sqlite.NativeDB.prepare(Native Method)
Console	: [19:06:29 WARN]: 	at org.sqlite.DB.prepare(DB.java:123)
Console	: [19:06:29 WARN]: 	at org.sqlite.PrepStmt.<init>(PrepStmt.java:42)
Console	: [19:06:29 WARN]: 	at org.sqlite.Conn.prepareStatement(Conn.java:404)
Console	: [19:06:29 WARN]: 	at org.sqlite.Conn.prepareStatement(Conn.java:399)
Console	: [19:06:29 WARN]: 	at org.sqlite.Conn.prepareStatement(Conn.java:383)
Console	: [19:06:29 WARN]: 	at net.licks92.WirelessRedstone.Storage.SQLiteStorage.getWirelessChannel(SQLiteStorage.java:525)
Console	: [19:06:29 WARN]: 	at net.licks92.WirelessRedstone.Storage.SQLiteStorage.getAllChannels(SQLiteStorage.java:471)
Console	: [19:06:29 WARN]: 	at net.licks92.WirelessRedstone.Storage.SQLiteStorage.getAllChannels(SQLiteStorage.java:440)
Console	: [19:06:29 WARN]: 	at net.licks92.WirelessRedstone.Storage.SQLiteStorage.initiate(SQLiteStorage.java:930)
Console	: [19:06:29 WARN]: 	at net.licks92.WirelessRedstone.Storage.SQLiteStorage.initStorage(SQLiteStorage.java:55)
Console	: [19:06:29 WARN]: 	at net.licks92.WirelessRedstone.WirelessRedstone.onEnable(WirelessRedstone.java:150)
Console	: [19:06:30 WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
Console	: [19:06:30 WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340)
Console	: [19:06:30 WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
Console	: [19:06:30 WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357)
Console	: [19:06:30 WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317)
Console	: [19:06:30 WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:414)
Console	: [19:06:30 WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:378)
Console	: [19:06:30 WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:333)
Console	: [19:06:30 WARN]: 	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:263)
Console	: [19:06:30 WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525)
Console	: [19:06:30 WARN]: 	at java.lang.Thread.run(Thread.java:745)
Console	: [19:06:30 ERROR]: Error occurred while enabling WirelessRedstone v3.0.0 (Is it up to date?)
Console	: java.lang.NullPointerException
Console	: 	at net.licks92.WirelessRedstone.Storage.SQLiteStorage.initiate(SQLiteStorage.java:931) ~[?:?]
Console	: 	at net.licks92.WirelessRedstone.Storage.SQLiteStorage.initStorage(SQLiteStorage.java:55) ~[?:?]
Console	: 	at net.licks92.WirelessRedstone.WirelessRedstone.onEnable(WirelessRedstone.java:150) ~[?:?]
Console	: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigot.jar:git-Spigot-21fe707-e1ebe52]
Console	: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot.jar:git-Spigot-21fe707-e1ebe52]
Console	: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot.jar:git-Spigot-21fe707-e1ebe52]
Console	: 	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357) [spigot.jar:git-Spigot-21fe707-e1ebe52]
Console	: 	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317) [spigot.jar:git-Spigot-21fe707-e1ebe52]
Console	: 	at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:414) [spigot.jar:git-Spigot-21fe707-e1ebe52]
Console	: 	at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:378) [spigot.jar:git-Spigot-21fe707-e1ebe52]
Console	: 	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:333) [spigot.jar:git-Spigot-21fe707-e1ebe52]
Console	: 	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:263) [spigot.jar:git-Spigot-21fe707-e1ebe52]
Console	: 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525) [spigot.jar:git-Spigot-21fe707-e1ebe52]
Console	: 	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_102]
```

Please note that the exception occurred on v3.0.0 beta 2 is as follows:
```
Console	: [19:22:34 INFO]: [WirelessRedstone] Enabling WirelessRedstone v3.0.0-beta.2
Console	: [19:22:34 INFO]: [WirelessRedstone][WARNING] You've set the language to default in your configuration. This language isn't available. The plugin will use English as language.
Console	: [19:22:44 WARN]: java.sql.SQLException: [SQLITE_ERROR] SQL error or missing database (unrecognized token: "0422y")
Console	: [19:22:44 WARN]: 	at org.sqlite.DB.newSQLException(DB.java:383)
Console	: [19:22:44 WARN]: 	at org.sqlite.DB.newSQLException(DB.java:387)
Console	: [19:22:44 WARN]: 	at org.sqlite.DB.throwex(DB.java:374)
Console	: [19:22:44 WARN]: 	at org.sqlite.NativeDB.prepare(Native Method)
Console	: [19:22:44 WARN]: 	at org.sqlite.DB.prepare(DB.java:123)
Console	: [19:22:44 WARN]: 	at org.sqlite.PrepStmt.<init>(PrepStmt.java:42)
Console	: [19:22:44 WARN]: 	at org.sqlite.Conn.prepareStatement(Conn.java:404)
Console	: [19:22:44 WARN]: 	at org.sqlite.Conn.prepareStatement(Conn.java:399)
Console	: [19:22:44 WARN]: 	at org.sqlite.Conn.prepareStatement(Conn.java:383)
Console	: [19:22:44 WARN]: 	at net.licks92.WirelessRedstone.Storage.SQLiteStorage.getWirelessChannel(SQLiteStorage.java:516)
Console	: [19:22:44 WARN]: 	at net.licks92.WirelessRedstone.Storage.SQLiteStorage.getAllChannels(SQLiteStorage.java:469)
Console	: [19:22:44 WARN]: 	at net.licks92.WirelessRedstone.GlobalCache.updateList(GlobalCache.java:52)
Console	: [19:22:44 WARN]: 	at net.licks92.WirelessRedstone.GlobalCache.updateAllSigns(GlobalCache.java:43)
Console	: [19:22:44 WARN]: 	at net.licks92.WirelessRedstone.GlobalCache.update(GlobalCache.java:87)
Console	: [19:22:44 WARN]: 	at net.licks92.WirelessRedstone.GlobalCache.<init>(GlobalCache.java:23)
Console	: [19:22:44 WARN]: 	at net.licks92.WirelessRedstone.Main.onEnable(Main.java:147)
Console	: [19:22:44 WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
Console	: [19:22:44 WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340)
Console	: [19:22:44 WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
Console	: [19:22:44 WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357)
Console	: [19:22:44 WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317)
Console	: [19:22:44 WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:414)
Console	: [19:22:44 WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:378)
Console	: [19:22:44 WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:333)
Console	: [19:22:44 WARN]: 	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:263)
Console	: [19:22:44 WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525)
Console	: [19:22:44 WARN]: 	at java.lang.Thread.run(Thread.java:745)
Console	: [19:23:03 INFO]: [WirelessRedstone] Plugin is now loaded
```
On beta 2, the plugin successfully(?) loaded (still continue throwing exceptions) but the version you gave me on this issue page does not work at all.

**Comment by Bart-0110** [comment]
Thank you for testing it. I will rollback my change.

Can you check if table 0422y exist and if it exist can you give the records of it?

**Comment by herm1ne** [comment]
Structure of `0422y`:
[![https://umcs.gyazo.com/0dd77e3681c2a3ebd4adbd7e99dfa581](https://t.gyazo.com/teams/umcs/0dd77e3681c2a3ebd4adbd7e99dfa581.png)](https://umcs.gyazo.com/0dd77e3681c2a3ebd4adbd7e99dfa581)

Contents of `0422y`:
[![https://umcs.gyazo.com/b8ab890d2646735761aa3f9399193245](https://t.gyazo.com/teams/umcs/b8ab890d2646735761aa3f9399193245.png)](https://umcs.gyazo.com/b8ab890d2646735761aa3f9399193245)

**Comment by Bart-0110** [comment]
Well, I found the problem. It isn't the scheme, I was requesting the tables without escaping the strings (see [e8ba6c1](https://github.com/WirelessRedstoneGroup/WirelessRedstone/commit/e8ba6c187af2a5813d1d43d272998bbc4d354585)). 

Without escaping it SQLite couldn't process it.
