### ISSUE TITLE
WR 3.0.1 Signname with "-" not allowed?

### ISSUE THREAD

**Issue by wapjoe** [WirelessRedstoneGroup/WirelessRedstone#173]
Since today it's not possible to created Signs with '-' in the Name, like 'Test-a'.

wapjoe

**Comment by wapjoe** [comment]
Also since today i'm getting the following Sqlite-Errors:
`[22:22:19 INFO]: [WirelessRedstone] Enabling WirelessRedstone v3.0.1
[22:22:20 WARN]: org.sqlite.SQLiteException: [SQLITE_LOCKED]  A table in the database is locked (database table is locked)
[22:22:20 WARN]:        at org.sqlite.core.DB.newSQLException(DB.java:909)
[22:22:20 WARN]:        at org.sqlite.core.DB.newSQLException(DB.java:921)
[22:22:20 WARN]:        at org.sqlite.core.DB.execute(DB.java:822)
[22:22:20 WARN]:        at org.sqlite.jdbc3.JDBC3PreparedStatement.execute(JDBC3PreparedStatement.java:53)
[22:22:20 WARN]:        at net.licks92.WirelessRedstone.Libs.SQLite$1.run(SQLite.java:60)
[22:22:20 WARN]:        at java.util.TimerThread.mainLoop(Timer.java:555)
[22:22:20 WARN]:        at java.util.TimerThread.run(Timer.java:505)
[22:22:20 WARN]: org.sqlite.SQLiteException: [SQLITE_LOCKED]  A table in the database is locked (database table is locked)
[22:22:20 WARN]:        at org.sqlite.core.DB.newSQLException(DB.java:909)
[22:22:20 WARN]:        at org.sqlite.core.DB.newSQLException(DB.java:921)
[22:22:20 WARN]:        at org.sqlite.core.DB.execute(DB.java:822)
[22:22:20 WARN]:        at org.sqlite.jdbc3.JDBC3PreparedStatement.execute(JDBC3PreparedStatement.java:53)
[22:22:20 WARN]:        at net.licks92.WirelessRedstone.Libs.SQLite$1.run(SQLite.java:60)
[22:22:20 WARN]:        at java.util.TimerThread.mainLoop(Timer.java:555)
[22:22:20 WARN]:        at java.util.TimerThread.run(Timer.java:505)
[22:22:21 INFO]: [WirelessRedstone] Plugin is now loaded
`

**Comment by Bart-0110** [comment]
Thank you for pointing out that you can't use '-'

For the exception, how many channels/sign do you approximately have?

**Comment by wapjoe** [comment]
Hi Bart,

in my newest .db, i have more then 140 channels, many are unused, but WR didnt delete them. I see now, that the Channels with - (e.g. Test-a) written as _char_45_ like Test_char_45_a, in the .db.

At the moment i downgraded to beta2, there it still works.

May WR havent got enough permissions to delete tables in the .db? MC is runnig at ubuntu 16.04 64 bit, if its relevant.

**Comment by Bart-0110** [comment]
Do you get the exceptions on beta2?

**Comment by wapjoe** [comment]
Not the same, this from beta2:
`[16:20:27 WARN]: [WirelessRedstone] Task #268 for WirelessRedstone v3.0.0-beta.2 generated an exception
java.lang.NullPointerException
        at net.licks92.WirelessRedstone.Listeners.PlayerListener$1.run(PlayerListener.java:30) ~[?:?]
        at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.11.2.jar:git-Spigot-7d78b81-270755d]
        at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [spigot-1.11.2.jar:git-Spigot-7d78b81-270755d]
        at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:730) [spigot-1.11.2.jar:git-Spigot-7d78b81-270755d]
        at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.11.2.jar:git-Spigot-7d78b81-270755d]
        at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675) [spigot-1.11.2.jar:git-Spigot-7d78b81-270755d]
        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574) [spigot-1.11.2.jar:git-Spigot-7d78b81-270755d]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]`

**Comment by wapjoe** [comment]
btw: present signs i can use normaly, but it isnt possible to create an new one with the same Channename, at 3.0.1.

**Comment by Bart-0110** [comment]
Can you try this version?

[WirelessRedstone.zip](https://github.com/WirelessRedstoneGroup/WirelessRedstone/files/696792/WirelessRedstone.zip)

**Comment by wapjoe** [comment]
This works perfekt! Create with '-' and delete unused channels works!

Fine job, thanks a lot :-)

**Comment by Bart-0110** [comment]
So this fix both issues?

**Comment by wapjoe** [comment]
It looks so!

**Comment by wapjoe** [comment]
Great! The directly registration of the signs, is now also fixed or realised, I don't have click the sign again, after paste!
