### ISSUE TITLE
No /wr list command, "spam" in console

### ISSUE THREAD

**Issue by pnndzwdz** [WirelessRedstoneGroup/WirelessRedstone#178]
Hi, I have a problem with WR 3.0.3 version, because I separated my worlds to servers and WR send in my minecraft console many mistakes. I thought, that WR channels from world, which I separated causes these mistakes. I wanted remove other-worlds channels, but WR command "/wr list [page]" doesnt work and database is coded. In that case, how do I delete unnecessary channels? 

I send error inscription from console. (for a 3.0.3 version it's the same)
[Server thread/ERROR]: Could not pass event BlockRedstoneEvent to WirelessRedstone v2.6.3
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[mc.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[mc.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [mc.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [mc.jar:git-Spigot-21fe707-e1ebe52]
	at net.licks92.WirelessRedstone.Listeners.WirelessBlockListener$2.run(WirelessBlockListener.java:299) [WirelessRedstone-2.6.3.jar:?]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) [mc.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [mc.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723) [mc.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [mc.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [mc.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [mc.jar:git-Spigot-21fe707-e1ebe52]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
Caused by: java.lang.NullPointerException
	at org.bukkit.Location.getBlock(Location.java:87) ~[mc.jar:git-Spigot-21fe707-e1ebe52]
	at net.licks92.WirelessRedstone.Channel.WirelessTransmitter.isActive(WirelessTransmitter.java:42) ~[?:?]
	at net.licks92.WirelessRedstone.Channel.WirelessChannel.isOn(WirelessChannel.java:436) ~[?:?]
	at net.licks92.WirelessRedstone.Channel.WirelessChannel.toggle(WirelessChannel.java:195) ~[?:?]
	at net.licks92.WirelessRedstone.Listeners.WirelessBlockListener.onBlockRedstoneChange(WirelessBlockListener.java:218) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor93.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_121]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_121]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[mc.jar:git-Spigot-21fe707-e1ebe52]
	... 11 more

**Comment by Bart-0110** [comment]
Because you separated worlds the plugin is a bit confused. You can purge all data that cannot be found by the plugin with /wra purge

**Comment by Bart-0110** [comment]
Can you also maybe send the stack trace in version 3.0.3? There is some new code formatting so it will be easier to find the problem in version 3.0.3 with the stack trace from 3.0.3.

**Comment by Bart-0110** [comment]
Fixed in v3.0.4

**Comment by Bart-0110** [comment]
`how do I delete unnecessary channels`

/wra purge

This will delete any channel that can't be found the wolds.
