### ISSUE TITLE
Can't create signals

### ISSUE THREAD

**Issue by ItsPueh** [WirelessRedstoneGroup/WirelessRedstone#182]
Hey,

I've got a problem with my WR. I'm trying to create a signals with [transmitter] on a sign, but it won't give any messages is the chat. Nor will it give an error in the console.

I don't have a lot of plugins, just a few; AsyncWorldEdit (+injector), CoreProtect, Bookshelfs, WorldEdit, my own plugin (which is a basic version of Essentials), Essentials (+chat), AntiSpam, BetterChairs, HolographicDisplays, LWC, ChatColor, IronElevators and WR.

Spigot version: 1.11.2-R0.1-SNAPSHOT
WR version: 3.0.3

If you could help me, that would be great.

Thanks in advance!

**Comment by Bart-0110** [comment]
Try 

```
[wrt]
<channelName>
```

**Comment by ItsPueh** [comment]
That doesn't work either. I've found something in the console when enabling WR:
`[19:05:06 INFO]: [WirelessRedstone] Enabling WirelessRedstone v3.0.3
[19:05:06 ERROR]: Error occurred while enabling WirelessRedstone v3.0.3 (Is it up to date?)
java.lang.NoClassDefFoundError: org/sqlite/NativeDB
        at java.lang.ClassLoader$NativeLibrary.load(Native Method) ~[?:1.8.0_121]
        at java.lang.ClassLoader.loadLibrary0(Unknown Source) ~[?:1.8.0_121]
        at java.lang.ClassLoader.loadLibrary(Unknown Source) ~[?:1.8.0_121]
        at java.lang.Runtime.load0(Unknown Source) ~[?:1.8.0_121]
        at java.lang.System.load(Unknown Source) ~[?:1.8.0_121]
        at org.sqlite.SQLiteJDBCLoader.loadNativeLibrary(SQLiteJDBCLoader.java:268) ~[spigot-1.11.2.jar:git-Spigot-0b1090d-7fdc749]
        at org.sqlite.SQLiteJDBCLoader.loadSQLiteNativeLibrary(SQLiteJDBCLoader.java:304) ~[spigot-1.11.2.jar:git-Spigot-0b1090d-7fdc749]
        at org.sqlite.SQLiteJDBCLoader.initialize(SQLiteJDBCLoader.java:64) ~[spigot-1.11.2.jar:git-Spigot-0b1090d-7fdc749]
        at org.sqlite.core.NativeDB.load(NativeDB.java:56) ~[spigot-1.11.2.jar:git-Spigot-0b1090d-7fdc749]
        at org.sqlite.core.CoreConnection.open(CoreConnection.java:211) ~[spigot-1.11.2.jar:git-Spigot-0b1090d-7fdc749]
        at org.sqlite.core.CoreConnection.<init>(CoreConnection.java:76) ~[spigot-1.11.2.jar:git-Spigot-0b1090d-7fdc749]
        at org.sqlite.jdbc3.JDBC3Connection.<init>(JDBC3Connection.java:24) ~[spigot-1.11.2.jar:git-Spigot-0b1090d-7fdc749]
        at org.sqlite.jdbc4.JDBC4Connection.<init>(JDBC4Connection.java:24) ~[spigot-1.11.2.jar:git-Spigot-0b1090d-7fdc749]
        at org.sqlite.SQLiteConnection.<init>(SQLiteConnection.java:45) ~[spigot-1.11.2.jar:git-Spigot-0b1090d-7fdc749]
        at org.sqlite.JDBC.createConnection(JDBC.java:114) ~[spigot-1.11.2.jar:git-Spigot-0b1090d-7fdc749]
        at org.sqlite.JDBC.connect(JDBC.java:88) ~[spigot-1.11.2.jar:git-Spigot-0b1090d-7fdc749]
        at java.sql.DriverManager.getConnection(Unknown Source) ~[?:1.8.0_121]
        at java.sql.DriverManager.getConnection(Unknown Source) ~[?:1.8.0_121]
        at net.licks92.WirelessRedstone.Libs.SQLite.<init>(SQLite.java:52) ~[?:?]
        at net.licks92.WirelessRedstone.Storage.SQLiteStorage.<init>(SQLiteStorage.java:50) ~[?:?]
        at net.licks92.WirelessRedstone.Storage.StorageManager.<init>(StorageManager.java:16) ~[?:?]
        at net.licks92.WirelessRedstone.WirelessRedstone.onEnable(WirelessRedstone.java:148) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:271) ~[spigot-1.11.2.jar:git-Spigot-0b1090d-7fdc749]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot-1.11.2.jar:git-Spigot-0b1090d-7fdc749]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot-1.11.2.jar:git-Spigot-0b1090d-7fdc749]
        at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugin(CraftServer.java:376) [spigot-1.11.2.jar:git-Spigot-0b1090d-7fdc749]
        at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugins(CraftServer.java:326) [spigot-1.11.2.jar:git-Spigot-0b1090d-7fdc749]
        at net.minecraft.server.v1_11_R1.MinecraftServer.t(MinecraftServer.java:419) [spigot-1.11.2.jar:git-Spigot-0b1090d-7fdc749]
        at net.minecraft.server.v1_11_R1.MinecraftServer.l(MinecraftServer.java:380) [spigot-1.11.2.jar:git-Spigot-0b1090d-7fdc749]
        at net.minecraft.server.v1_11_R1.MinecraftServer.a(MinecraftServer.java:335) [spigot-1.11.2.jar:git-Spigot-0b1090d-7fdc749]
        at net.minecraft.server.v1_11_R1.DedicatedServer.init(DedicatedServer.java:272) [spigot-1.11.2.jar:git-Spigot-0b1090d-7fdc749]
        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:542) [spigot-1.11.2.jar:git-Spigot-0b1090d-7fdc749]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_121]
Caused by: java.lang.ClassNotFoundException: org.sqlite.NativeDB
        at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_121]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_121]
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source) ~[?:1.8.0_121]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_121]
        ... 33 more`

**Comment by Bart-0110** [comment]
> Do transmitters stay a sign when they're getting powered?

Yes

Your error is a bit weird, which kind of server do you have (spigot/bukkit/forge) and can you try redownloading the plugin?

**Comment by ItsPueh** [comment]
Apparently I've fixed it. I had an old version of LWC, which I updated, and after the restart WR worked again. My guess would be that LWC crashed WR. All the commands weren't working either, but everything works now.

Thank you for your time
