### ISSUE TITLE
WirelessRedstone doesn't work anylonger..

### ISSUE THREAD

**Issue by JonasFS2002** [WirelessRedstoneGroup/WirelessRedstone#196]
When I came to my server today, the redstone did not work anymore. I activated the plates again with the help of world edit. When I tried, the signs remained activated so the redstone torch remained. I saw in the console an error if the plugin was up to date ... I removed the plugin and installed the new version, now I get the following message: 
[ERROR] Error occurred while enabling WirelessRedstone v3.0.5 (Is it up to date?)
How can I fix the plugin and all the signs without having to replace them all? 
(I play on a 1.8 server)

**Comment by JonasFS2002** [comment]
The complete error:
[ERROR] Error occurred while enabling WirelessRedstone v3.0.5 (Is it up to date?)

java.lang.NoClassDefFoundError: com/google/gson/Gson

at net.licks92.WirelessRedstone.String.StringManager.<init>(StringManager.java:78) ~[?:?]

at net.licks92.WirelessRedstone.WirelessRedstone.onEnable(WirelessRedstone.java:150) ~[?:?]

at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigot-1.8.jar:git-Spigot-550ebac-7019900]

at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:335) [spigot-1.8.jar:git-Spigot-550ebac-7019900]

at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot-1.8.jar:git-Spigot-550ebac-7019900]

at org.bukkit.craftbukkit.v1_8_R1.CraftServer.loadPlugin(CraftServer.java:356) [spigot-1.8.jar:git-Spigot-550ebac-7019900]

at org.bukkit.craftbukkit.v1_8_R1.CraftServer.enablePlugins(CraftServer.java:316) [spigot-1.8.jar:git-Spigot-550ebac-7019900]

at net.minecraft.server.v1_8_R1.MinecraftServer.q(MinecraftServer.java:402) [spigot-1.8.jar:git-Spigot-550ebac-7019900]

at net.minecraft.server.v1_8_R1.MinecraftServer.k(MinecraftServer.java:370) [spigot-1.8.jar:git-Spigot-550ebac-7019900]

at net.minecraft.server.v1_8_R1.MinecraftServer.a(MinecraftServer.java:325) [spigot-1.8.jar:git-Spigot-550ebac-7019900]

at net.minecraft.server.v1_8_R1.DedicatedServer.init(DedicatedServer.java:211) [spigot-1.8.jar:git-Spigot-550ebac-7019900]

at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:505) [spigot-1.8.jar:git-Spigot-550ebac-7019900]

at java.lang.Thread.run(Thread.java:748) [?:1.8.0_172]

Caused by: java.lang.ClassNotFoundException: com.google.gson.Gson

at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_172]

at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot-1.8.jar:git-Spigot-550ebac-7019900]

at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot-1.8.jar:git-Spigot-550ebac-7019900]

at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_172]

at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_172]

... 13 more

**Comment by Bart-0110** [comment]
Your Minecraft server file is broken. You should re-download it.

I also highly recommend updating to a newer Minecraft version (like 1.12/1.13). If you don't want this for whatever reason you should at least update to 1.8.8 (instead of 1.8.0).
