### ISSUE TITLE
Wall receiver dissapears after activation

### ISSUE THREAD

**Issue by SenneVanderAuwera** [WirelessRedstoneGroup/WirelessRedstone#200]
After I couple a transmitter with a receiver it works fine until i click the button. The receiver changes into a redstone torch and then dissapears, the sign goes away too. And it doesn't work after that.

It does seem to work on wall signs

**Comment by Bart-0110** [comment]
Thanks for reporting I'll look into it next week. This may be linked to #199.

**Comment by houtknots** [comment]
I'm having the same problem as @SenneVanderAuwera 

https://media.houtknots.nl/files/2019-02-25_18-40-22.mp4

**Comment by houtknots** [comment]
@Bart-0110 Do you have an update about the status of the problem? can I do anything that may help?

**Comment by Bart-0110** [comment]
Can you see if the direction in the config is correct? And what is the direction where you are having a problem?

**Comment by houtknots** [comment]
isWallSign: true
    x: 227
    y: 66
    z: 172
    direction: NORTH

The Direction is Correct I tried al 4 Directions

**Comment by houtknots** [comment]
@Bart-0110 Do you have an update on the problem?

**Comment by RuudSchutten** [comment]
@Bart-0110 Do you have an update on the problem?

**Comment by Bart-0110** [comment]
If anyone has this problem can you try the latest beta?
This should also add basic 1.14 compatibility.

[https://github.com/WirelessRedstoneGroup/WirelessRedstone/releases/tag/v4.0.0-beta.3](https://github.com/WirelessRedstoneGroup/WirelessRedstone/releases/tag/v4.0.0-beta.3)

**Comment by houtknots** [comment]
@bart-0110 I will be trying it out tomorrow and give you all the results 👌🏻

**Comment by RuudSchutten** [comment]
Als ik nu een sign aanmaak doet hij het niet. De sign doet het enkel via /wr create ...........

**Comment by RuudSchutten** [comment]
If I make a sign now, he won't do it. The sign only works via /wr create ...............

**Comment by RuudSchutten** [comment]
Standing signs work, wall signs don't.

**Comment by Bart-0110** [comment]
See the latest beta. [https://github.com/WirelessRedstoneGroup/WirelessRedstone/releases/tag/v4.0.0-beta.8](https://github.com/WirelessRedstoneGroup/WirelessRedstone/releases/tag/v4.0.0-beta.8). This should be fixed.

**Comment by iqfx** [comment]
now i get this error when placing a receiver on a wall: 
Using version 4.0.1 and Paper version git-Paper-641 (MC: 1.13.2) 

` [08:52:18 ERROR]: Could not pass event BlockRedstoneEvent to WirelessRedstone v4.0.1
java.lang.ClassCastException: org.bukkit.craftbukkit.v1_13_R2.block.impl.CraftWallSign cannot be cast to org.bukkit.block.data.type.RedstoneWallTorch
at net.licks92.WirelessRedstone.Compat.InternalBlockData_1_13.setRedstoneWallTorch(InternalBlockData_1_13.java:97) ~[?:?]
at net.licks92.WirelessRedstone.Signs.WirelessReceiver.changeState(WirelessReceiver.java:92) ~[?:?]
at net.licks92.WirelessRedstone.Signs.WirelessReceiver.turnOn(WirelessReceiver.java:52) ~[?:?]
at net.licks92.WirelessRedstone.Signs.WirelessChannel.lambda$turnOn$0(WirelessChannel.java:99) ~[?:?]
at java.util.ArrayList.forEach(ArrayList.java:1257) ~[?:1.8.0_212]
at net.licks92.WirelessRedstone.Signs.WirelessChannel.turnOn(WirelessChannel.java:99) ~[?:?]
at net.licks92.WirelessRedstone.Signs.WirelessChannel.turnOn(WirelessChannel.java:75) ~[?:?]
at net.licks92.WirelessRedstone.Listeners.BlockListener.updateRedstonePower(BlockListener.java:346) ~[?:?]
at net.licks92.WirelessRedstone.Listeners.BlockListener.handleRedstoneEvent(BlockListener.java:315) ~[?:?]
at net.licks92.WirelessRedstone.Listeners.BlockListener.on(BlockListener.java:51) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor13.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.13.2.jar:git-Paper-641]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.13.2.jar:git-Paper-641]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:66) ~[patched_1.13.2.jar:git-Paper-641]
at net.licks92.WirelessRedstone.Sentry.EventExceptionHandler$ExceptionRegisteredListener.callEvent(EventExceptionHandler.java:48) ~[?:?]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:520) ~[patched_1.13.2.jar:git-Paper-641]
at net.minecraft.server.v1_13_R2.BlockButtonAbstract.interact(BlockButtonAbstract.java:87) ~[patched_1.13.2.jar:git-Paper-641]
at net.minecraft.server.v1_13_R2.IBlockData.interact(IBlockData.java:249) ~[patched_1.13.2.jar:git-Paper-641]
at net.minecraft.server.v1_13_R2.PlayerInteractManager.a(PlayerInteractManager.java:524) ~[patched_1.13.2.jar:git-Paper-641]
at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1348) ~[patched_1.13.2.jar:git-Paper-641]
at net.minecraft.server.v1_13_R2.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37) ~[patched_1.13.2.jar:git-Paper-641]
at net.minecraft.server.v1_13_R2.PacketPlayInUseItem.a(PacketPlayInUseItem.java:5) ~[patched_1.13.2.jar:git-Paper-641]
at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:15) ~[patched_1.13.2.jar:git-Paper-641]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_212]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_212]
at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:108) ~[patched_1.13.2.jar:git-Paper-641]
at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1018) ~[patched_1.13.2.jar:git-Paper-641]
at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-641]
at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:940) ~[patched_1.13.2.jar:git-Paper-641]
at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:837) ~[patched_1.13.2.jar:git-Paper-641]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]`

**Comment by RuudSchutten** [comment]
Hey Bart, i found a new bug. https://gyazo.com/05213ea73d8d955ae8bd2fc9ddf805ed

**Comment by Bart-0110** [comment]
> Hey Bart, i found a new bug. https://gyazo.com/05213ea73d8d955ae8bd2fc9ddf805ed

Is this a newly placed sign or an old one?
