### ISSUE TITLE
Repeating error ChunkUnloadEvent on 1.14.1 spigot server

### ISSUE THREAD

**Issue by TDLaouer** [WirelessRedstoneGroup/WirelessRedstone#204]
Hello,
I am getting this error in a loop while the server is running. Everyone can play fine and the mod works, but it seems to cause some lag. Thanks for the help.

```
[12:53:28] [Server thread/ERROR]: Could not pass event ChunkUnloadEvent to WirelessRedstone v3.0.6
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:320) ~[spigot-1.14.1.jar:git-Spigot-03bd4b0-49e15b4]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-1.14.1.jar:git-Spigot-03bd4b0-49e15b4]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:520) ~[spigot-1.14.1.jar:git-Spigot-03bd4b0-49e15b4]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:505) ~[spigot-1.14.1.jar:git-Spigot-03bd4b0-49e15b4]
        at net.minecraft.server.v1_14_R1.PlayerChunkMap.lambda$14(PlayerChunkMap.java:354) ~[spigot-1.14.1.jar:git-Spigot-03bd4b0-49e15b4]
        at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:656) [?:1.8.0_212]
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:632) [?:1.8.0_212]
        at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442) [?:1.8.0_212]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(SourceFile:135) [spigot-1.14.1.jar:git-Spigot-03bd4b0-49e15b4]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(SourceFile:114) [spigot-1.14.1.jar:git-Spigot-03bd4b0-49e15b4]
        at net.minecraft.server.v1_14_R1.ChunkProviderServer$a.executeNext(ChunkProviderServer.java:496) [spigot-1.14.1.jar:git-Spigot-03bd4b0-49e15b4]
        at net.minecraft.server.v1_14_R1.ChunkProviderServer.runTasks(ChunkProviderServer.java:192) [spigot-1.14.1.jar:git-Spigot-03bd4b0-49e15b4]
        at net.minecraft.server.v1_14_R1.MinecraftServer.aW(MinecraftServer.java:904) [spigot-1.14.1.jar:git-Spigot-03bd4b0-49e15b4]
        at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:888) [spigot-1.14.1.jar:git-Spigot-03bd4b0-49e15b4]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeAll(SourceFile:99) [spigot-1.14.1.jar:git-Spigot-03bd4b0-49e15b4]
        at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:871) [spigot-1.14.1.jar:git-Spigot-03bd4b0-49e15b4]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:805) [spigot-1.14.1.jar:git-Spigot-03bd4b0-49e15b4]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: java.lang.NoSuchMethodError: org.bukkit.event.world.ChunkUnloadEvent.isCancelled()Z
        at net.licks92.WirelessRedstone.Listeners.WorldListener.onChunkUnload(WorldListener.java:18) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_212]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_212]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316) ~[spigot-1.14.1.jar:git-Spigot-03bd4b0-49e15b4]
        ... 17 more
```

**Comment by Bart-0110** [comment]
Change `cancelChunkUnloads` to false in the config

**Comment by TDLaouer** [comment]
That fixed it. Thanks.

**Comment by markthetechie** [comment]
We are playing with 1.14.3 encountering the same problem.
Setting cancelChunkUnload=false doesnt seem to change anything for us.

**Comment by markthetechie** [comment]
I recognized we were not using the newest version. Problem does not appear with cancelChunkUnload=false anymore. Sorry for bothering
