### ISSUE TITLE
Task exception

### ISSUE THREAD

**Issue by ArtelGG** [WirelessRedstoneGroup/WirelessRedstone#208]
## Bug report

**Plugin version:** 4.0.0-beta.8
**Server version:** PaperSpigot 1.14.4-b135

**Seen results:**  
I was right-clicking signs with an empty hand to make sure they were all updated and working correctly and I noticed an error pop up in my console.
```
26.07 05:15:41 [Server] WARN [WirelessRedstone] Task #167 for WirelessRedstone v4.0.0-beta.8 generated an exception
26.07 05:15:41 [Server] INFO java.lang.IllegalArgumentException: Block needs to be a org.bukkit.block.data.Rotatable found class org.bukkit.craftbukkit.v1_14_R1.block.impl.CraftWallSign
26.07 05:15:41 [Server] INFO at net.licks92.WirelessRedstone.Compat.InternalBlockData_1_13.getSignRotation(InternalBlockData_1_13.java:50) ~[?:?]
26.07 05:15:41 [Server] INFO at net.licks92.WirelessRedstone.Listeners.BlockListener.lambda$on$0(BlockListener.java:160) ~[?:?]
26.07 05:15:41 [Server] INFO at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.14.4.jar:git-Paper-135]
26.07 05:15:41 [Server] INFO at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452) ~[patched_1.14.4.jar:git-Paper-135]
26.07 05:15:41 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1144) ~[patched_1.14.4.jar:git-Paper-135]
26.07 05:15:41 [Server] INFO at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:420) ~[patched_1.14.4.jar:git-Paper-135]
26.07 05:15:41 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1076) ~[patched_1.14.4.jar:git-Paper-135]
26.07 05:15:41 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:920) ~[patched_1.14.4.jar:git-Paper-135]
26.07 05:15:41 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
```

**Expected results:**  
There shouldn't be an error in the console.

**How to reproduce:**  
See "Seen results", I tried right-clicking all of my signs again and couldn't get it to happen again, so I assume a sign *wasn't* updated and it tried to update one and spit out the error.

**Additional info:**  
N/A

**Comment by Bart-0110** [comment]
Thanks for reporting the issue. 

I found the problem. Only standing signs are Rotables, WallSigns are Directionals. This causes ClassCasting issues. This should be fixed in the new release.
