### ISSUE TITLE
Error occurred while enabling WirelessRedstone v4.0.1

### ISSUE THREAD

**Issue by Tim16200** [WirelessRedstoneGroup/WirelessRedstone#212]
## Bug report

**I'm using version: v4.0.1
**I'm on Minecraft: 1.14.4
**I'm running: Spigot 1.14.4

**Seen results:**  
Plugin doesn't load correctly. I get an error message in commandprompt. no transmittor, receiver or /wra command works.

**Expected results:**  
plugin should have loaded correctly. and signs and command should work normally.

**How to reproduce:**  
plugin occurd wile using the spigot 1.14.4 file from getbukkit.org. I was using WirelessRedstone v4.0.1.

**Additional info:**  
Commandprompt says this:
[18:23:45] [Server thread/INFO]: [WirelessRedstone] Enabling WirelessRedstone v4.0.1
[18:23:45] [Server thread/INFO]: [WirelessRedstone] Updating SQLite database. This could take a while. As a precaution, a backup will be created.
[18:23:46] [Server thread/ERROR]: Error occurred while enabling WirelessRedstone v4.0.1 (Is it up to date?)
java.lang.IllegalArgumentException: No enum constant org.bukkit.block.BlockFace.0
        at java.lang.Enum.valueOf(Unknown Source) ~[?:1.8.0_221]
        at org.bukkit.block.BlockFace.valueOf(BlockFace.java:1) ~[spigot.jar:git-Spigot-9de398a-9c887d4]
        at net.licks92.WirelessRedstone.Storage.DatabaseClient.performUpdate1(DatabaseClient.java:469) ~[?:?]
        at net.licks92.WirelessRedstone.Storage.DatabaseClient.onUpdate(DatabaseClient.java:93) ~[?:?]
        at com.tylersuehr.sql.SQLiteOpenHelper.getWritableInstance(SQLiteOpenHelper.java:118) ~[?:?]
        at net.licks92.WirelessRedstone.Storage.DatabaseClient.<init>(DatabaseClient.java:52) ~[?:?]
        at net.licks92.WirelessRedstone.Storage.DatabaseClient.init(DatabaseClient.java:67) ~[?:?]
        at net.licks92.WirelessRedstone.Storage.StorageManager.moveStorageFromType(StorageManager.java:124) ~[?:?]
        at net.licks92.WirelessRedstone.Storage.YamlStorage.initStorage(YamlStorage.java:55) ~[?:?]
        at net.licks92.WirelessRedstone.WirelessRedstone.onEnable(WirelessRedstone.java:127) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[spigot.jar:git-Spigot-9de398a-9c887d4]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:352) [spigot.jar:git-Spigot-9de398a-9c887d4]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:417) [spigot.jar:git-Spigot-9de398a-9c887d4]
        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:461) [spigot.jar:git-Spigot-9de398a-9c887d4]
        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:375) [spigot.jar:git-Spigot-9de398a-9c887d4]
        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:449) [spigot.jar:git-Spigot-9de398a-9c887d4]
        at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:258) [spigot.jar:git-Spigot-9de398a-9c887d4]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:776) [spigot.jar:git-Spigot-9de398a-9c887d4]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]

**Comment by Bart-0110** [comment]
Is it possible to send the channels folder? I think that I found a solution but I need to test it.

**Comment by Tim16200** [comment]
Here are the files. I have found two channels files in my spigot server files. From the pictures you can see where they come from.

Kind regards,

Tim Schinkel

**Comment by Tim16200** [comment]
[channels file from picture 1.zip](https://github.com/WirelessRedstoneGroup/WirelessRedstone/files/3498026/channels.file.from.picture.1.zip)
[channels file from picture 2.zip](https://github.com/WirelessRedstoneGroup/WirelessRedstone/files/3498027/channels.file.from.picture.2.zip)
![Picture 1](https://user-images.githubusercontent.com/53912016/62960397-dbe1e900-bdfa-11e9-820c-07c54f23cab6.png)
![Picture 2](https://user-images.githubusercontent.com/53912016/62960398-dbe1e900-bdfa-11e9-8385-6b632a7ce83e.png)

**Comment by Bart-0110** [comment]
To be sure that I fixed the issue can you tell me the direction of the following WirelessRedstone signs (north, north_east, east, etc.):

- bbNederlands
x: -40    y: 79    z: 138    world: 'world'
x: -133    y: 65    z: 428    world: 'world'

- bbrider
x: -134    y: 65    z: 406    world: 'world'
x: -133    y: 65    z: 430    world: 'world'

- bbstart
x: -39    y: 65    z: 156    world: 'world'

**Comment by Tim16200** [comment]
Here are the directions of the WirelessRedstone signs. These signs come from a old server that’s not in use any more. I startes it up again to lookup the directions. These signs are not used on the server that I reported on GitHub. They come from an old server file that got a new world and spigot.jar file. but still had the old channels file of WirelessRedstone. I can send you the directions of the signs that I use on the server that I reported on GitHub. These signs have the names like: bvk, mtr and hsl.

With kind regards,

Tim Schinkel

**Comment by Bart-0110** [comment]
Hello, can you try [v4.0.2-beta.3](https://github.com/WirelessRedstoneGroup/WirelessRedstone/releases/download/v4.0.2-beta.3/WirelessRedstone-4.0.2-beta.3.jar)? The issue `No enum constant org.bukkit.block.BlockFace.0` is fixed. 

While the plugin can still throw a `[SQLITE_CONSTRAINT_PRIMARYKEY]` exception. This can be ignored. This happens because the WirelessChannel sign was stored two times instead of one and should not have any negative consequences.

**Comment by Tim16200** [comment]
I tried the v4.0.2-beta.3. But unfortunatly The signs stil don't work.

Here is a copy of the commandprompt.
[21:30:22] [Server thread/INFO]: [WirelessRedstone] Updating SQLite database. This could take a while. As a precaution, a backup will be created.
[21:30:26] [Server thread/INFO]: [WirelessRedstone] Database upgrade stage 1/2; Progress: 5%
[21:30:29] [Server thread/INFO]: [WirelessRedstone] Database upgrade stage 1/2; Progress: 10%
[21:30:32] [Server thread/INFO]: [WirelessRedstone] Database upgrade stage 1/2; Progress: 15%
[21:30:36] [Server thread/INFO]: [WirelessRedstone] Database upgrade stage 1/2; Progress: 20%
[21:30:39] [Server thread/INFO]: [WirelessRedstone] Database upgrade stage 1/2; Progress: 25%
[21:30:42] [Server thread/INFO]: [WirelessRedstone] Database upgrade stage 1/2; Progress: 30%
[21:30:45] [Server thread/INFO]: [WirelessRedstone] Database upgrade stage 1/2; Progress: 35%
[21:30:48] [Server thread/INFO]: [WirelessRedstone] Database upgrade stage 1/2; Progress: 40%
[21:30:51] [Server thread/INFO]: [WirelessRedstone] Database upgrade stage 1/2; Progress: 45%
[21:30:53] [Server thread/INFO]: [WirelessRedstone] Database upgrade stage 1/2; Progress: 50%
[21:30:56] [Server thread/INFO]: [WirelessRedstone] Database upgrade stage 1/2; Progress: 55%
[21:31:00] [Server thread/INFO]: [WirelessRedstone] Database upgrade stage 1/2; Progress: 60%
[21:31:03] [Server thread/INFO]: [WirelessRedstone] Database upgrade stage 1/2; Progress: 65%
[21:31:06] [Server thread/INFO]: [WirelessRedstone] Database upgrade stage 1/2; Progress: 70%
[21:31:09] [Server thread/INFO]: [WirelessRedstone] Database upgrade stage 1/2; Progress: 75%
[21:31:12] [Server thread/INFO]: [WirelessRedstone] Database upgrade stage 1/2; Progress: 80%
[21:31:15] [Server thread/INFO]: [WirelessRedstone] Database upgrade stage 1/2; Progress: 85%
[21:31:18] [Server thread/INFO]: [WirelessRedstone] Database upgrade stage 1/2; Progress: 90%
[21:31:21] [Server thread/INFO]: [WirelessRedstone] Database upgrade stage 1/2; Progress: 95%
[21:31:23] [Server thread/ERROR]: Error occurred while enabling WirelessRedstone v4.0.2-beta.3 (Is it up to date?)
java.lang.NoClassDefFoundError: org/apache/commons/io/IOUtils
        at net.licks92.wirelessredstone.storage.DatabaseClient.performUpdate1(DatabaseClient.java:596) ~[?:?]
        at net.licks92.wirelessredstone.storage.DatabaseClient.onUpdate(DatabaseClient.java:94) ~[?:?]
        at com.tylersuehr.sql.SQLiteOpenHelper.getWritableInstance(SQLiteOpenHelper.java:118) ~[?:?]
        at net.licks92.wirelessredstone.storage.DatabaseClient.<init>(DatabaseClient.java:53) ~[?:?]
        at net.licks92.wirelessredstone.storage.DatabaseClient.init(DatabaseClient.java:68) ~[?:?]
        at net.licks92.wirelessredstone.storage.StorageManager.moveStorageFromType(StorageManager.java:124) ~[?:?]
        at net.licks92.wirelessredstone.storage.YamlStorage.initStorage(YamlStorage.java:55) ~[?:?]
        at net.licks92.wirelessredstone.WirelessRedstone.onEnable(WirelessRedstone.java:130) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[spigot.jar:git-Spigot-9de398a-9c887d4]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:352) [spigot.jar:git-Spigot-9de398a-9c887d4]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:417) [spigot.jar:git-Spigot-9de398a-9c887d4]
        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:461) [spigot.jar:git-Spigot-9de398a-9c887d4]
        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:375) [spigot.jar:git-Spigot-9de398a-9c887d4]
        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:449) [spigot.jar:git-Spigot-9de398a-9c887d4]
        at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:258) [spigot.jar:git-Spigot-9de398a-9c887d4]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:776) [spigot.jar:git-Spigot-9de398a-9c887d4]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]
Caused by: java.lang.ClassNotFoundException: org.apache.commons.io.IOUtils
        at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_221]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:135) ~[spigot.jar:git-Spigot-9de398a-9c887d4]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:81) ~[spigot.jar:git-Spigot-9de398a-9c887d4]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_221]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_221]
        ... 17 more

**Comment by Bart-0110** [comment]
Can you try this new beta? https://github.com/WirelessRedstoneGroup/WirelessRedstone/releases/tag/v4.0.2-beta.4

**Comment by Tim16200** [comment]
Hello,
I tried the new beta and it loads now. It also activates the signs that where already placed. The only problem that I had is that when I tried to extend an existing channels with a transmittor the channel stayd active and did not want to deactivate. Also clicking on the signs did not work I had to activate the signs using a redstone torch or wire.

**Comment by Bart-0110** [comment]
Are you sure that all transmitters aren't activated? Since version 3 the receiver only turns off if all the transmitters are turned off. You can disable this in the config by changing `gateLogic` to `IGNORE`
